logging:
  receivers:
    TestApp:
      type: files
      include_paths:
        - /var/log/testapp.log

  processors:
    modify_severity:
      type: modify_fields
      fields:
        severity:
          copy_from: jsonPayload.level
          map_values:
            "info": "INFO"
            "warning": "WARN"

    testapp_json:
      type: parse_json

  service:
    pipelines:
      default_pipeline:
        receivers: [TestApp]
        processors: [testapp_json, modify_severity]